## Travis CI Integration
language: csharp
solution: Deblocus.sln

install:
  - nuget restore Deblocus.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild Deblocus.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe Deblocus.UnitTests/bin/Debug/Deblocus.UnitTests.dll
