## Travis CI Integration
language: csharp
solution: Deblocus.sln

# Handle git submodules yourself
git:
    submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - nuget restore xwt/Xwt.sln
  - nuget restore Deblocus.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - cd xwt && xbuild Xwt/Xwt.csproj && xbuild Xwt.Gtk/Xwt.Gtk.csproj && cd ..
  - xbuild Deblocus.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe Deblocus.UnitTests/bin/Debug/Deblocus.UnitTests.dll
